# Generated by Django 5.2 on 2025-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallecarrito_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecarrito',
            name='descuento_oferta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado por oferta en valor absoluto', max_digits=10),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='fecha_oferta_aplicada',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se detectó y aplicó la oferta', null=True),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='nombre_oferta',
            field=models.CharField(blank=True, help_text='Nombre de la oferta aplicada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio original del producto sin descuento', max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='descuento_oferta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado por oferta en valor absoluto', max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_oferta_aplicada',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se aplicó la oferta (para historial)', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_oferta',
            field=models.CharField(blank=True, help_text='Nombre de la oferta aplicada (para historial)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio original del producto sin descuento', max_digits=10),
        ),
    ]
